---
- name: my minecraft play
  hosts: minecraft
  become: true
  vars: 
    mcs_dir: /home/opc
    mcs_jar: server.jar
    session_name: mcserver
  tasks:
    - name: ping
      ping:
    - name: show hostname
      command: hostname  
    - name: Check screen for running sessions
      shell: screen -ls
      register: sessions
      failed_when: sessions.rc == 0 or sessions.rc >= 2       
    - name: Run mcserver
      command: screen -s {{ session_name }} -d -m java -Xmx1024M -Xms1024M -jar {{ mcs_dir }}/{{ mcs_jar }} nogui
      args:
        chdir: '{{ mcs_dir }}'
      when: sessions.stdout.find(session_name) == -1