---
- name: my minecraft play
  hosts: minecraft
  become: true
  #become_method: sudo
  #become_user: vagrant
  #remote-user: vagrant
  # vars:
  #   ansible-become-password: vagrant
  #   ansible-remote-password: vagrant
  vars: 
    mcs_dir: /home/opc
    mcs_jar: server.jar
    session_name: mcserver
  tasks:
    - name: ping
      ping:
    - name: show hostname
      command: hostname  
    - name : install java
      yum:
        name: jdk-17.aarch64
        lock_timeout: 180
    - name : download minecraft server
      become: yes
      get_url:
        url: https://launcher.mojang.com/v1/objects/125e5adf40c659fd3bce3e66e67a16bb49ecc1b9/server.jar
        dest: /home/opc
    - name : copy eula.txt for minecraft server 
      copy:
        src: ./eula.txt
        dest: /home/opc
    - name : add minecraft port udp on firewalld
      firewalld:
        port: 25565/udp
        permanent: true
        zone: public
        state: enabled 
        immediate: true
    - name : add minecraft port tcp on firewalld
      firewalld:
        port: 25565/tcp
        permanent: true
        zone: public
        state: enabled   
        immediate: true
    - name: reload service firewalld
      systemd:
        name: firewalld
        state: reloaded
    - name : install screen
      yum:
        name: screen
        lock_timeout: 180